#ifndef JOHNNY_CONFIG_H
#define JOHNNY_CONFIG_H

#define JOHNNY_BUFFER_SIZE 1024
#define JOHNNY_STACK_CONNECTIONS 1024
#define JOHNNY_EVENTS_BUFFER 1024
#define JOHNNY_PORT 5001
#define JOHNNY_INACTIVE_CONNECTION_TIMEOUT 30
#define JOHNNY_ROOT "/mnt/c/Users/JelleBouma/pictures/"

#endif //JOHNNY_CONFIG_H